name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  check-code:
    runs-on: macos-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
#        with:
#          submodules: recursive
#
#      - name: Set up Go
#        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
#        with:
#          go-version: 1.21.3
#
#      - name: Apply Patch
#        run: make apply-all-patch

      - name: Test
        run: |
          echo "auth_token length: ${#MACOS_CERTIFICATE}"
          exit 1
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
#
#      - name: Setup Codesign
#        run: |
#          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
#          security create-keychain -p action build.keychain
#          security default-keychain -s build.keychain
#          security unlock-keychain -p action build.keychain
#          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
#          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k action build.keychain
#        env:
#          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
#          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
#
#      - name: Build
#        run: make build
#        env:
#          CODESIGN_IDENTITY: ${{ secrets.MACOS_CODESIGN_IDENTITY }}
